Assets/Materials/Orange.mat, Assets/Scenes/CrimeSceneQuest.unity, Assets/Scenes/CrimeSceneQuest.unity.meta, ProjectSettings/ProjectVersion.txt
Added the basic blocks and objects.
=> Create crime scene quest

Assets/Scenes/ClimbingScene.unity, Assets/Scripts/Player/PlayerBehaviour.cs, Assets/Scripts/Player/PossessionBehaviour.cs
=> Fixed bugs

Assets/Scenes/BranchScenes/PoliceManBehaviourScene.unity, Assets/Scenes/BranchScenes/PoliceManBehaviourScene.unity.meta, Assets/Scripts/Entities/Humans/Police.cs, Assets/Scripts/Entities/Humans/PoliceManBehaviour.cs, Assets/Scripts/Entities/Humans/PoliceManBehaviour.cs.meta, Assets/Scripts/Interfaces/Entities/IHuman.cs, Assets/Scripts/Misc/Donut.cs, Assets/Scripts/Misc/Donut.cs.meta
=> Policeman Behaviour added

Assets/Scenes/BranchScenes/GlideScene.unity, Assets/Scenes/BranchScenes/GlideScene.unity.meta, Assets/Scripts/Entities/Abilities/GlideBehaviour.cs, Assets/Scripts/Entities/Abilities/GlideBehaviour.cs.meta, Assets/Scripts/Entities/Animals/BirdBehaviour.cs, Assets/Scripts/Entities/Animals/BirdBehaviour.cs.meta, Assets/Scripts/Entities/BaseMovement.cs
- Added GlideBehaviour.
- Added Bird Entity.
=> Made Gliding work

Assets/Scenes/BranchScenes/PathfindingScene.unity, Assets/Scenes/DevSandbox.unity, Assets/Scripts/Entities/Animals/BirdBehaviour.cs, Assets/Scripts/Entities/Animals/Cat.cs, Assets/Scripts/Entities/Animals/Dog.cs, Assets/Scripts/Entities/Animals/RatBehaviour.cs, Assets/Scripts/Entities/BaseMovement.cs, Assets/Scripts/Entities/EntityArea.cs, Assets/Scripts/Entities/Humans/Police.cs, Assets/Scripts/Entities/Humans/PoliceManBehaviour.cs, Assets/Scripts/Entities/Humans/VillagerBehaviour.cs, Assets/Scripts/Interfaces/Entities/IEntity.cs, Assets/Scripts/Player/PlayerBehaviour.cs, Assets/Scripts/Player/PossessionBehaviour.cs, Assets/Scripts/Sandbox/PossessableSanboxBox.cs
- Added patrolling
- Slightly altered EntityArea and made it work with pathfinding.
- Fixed small bugs regarding pathfinding and entities.
=> Pathfinding patrolling

Assets/Scenes/BranchScenes/CutsceneScene.unity, Assets/Scripts/CutScene/Action.cs
Custom editor didn't work out, so now there are headers.
=> Header for cutscene fields

Assets/Scenes/BranchScenes/LevitateScene.unity, Assets/Scripts/Interfaces/ILevitateable.cs, Assets/Scripts/Misc/LevitateableObject.cs, Assets/Scripts/Player/LevitateBehaviour.cs, Assets/Scripts/Player/PlayerBehaviour.cs
=> Levitation refactor

Assets/Scripts/Entities/BaseMovement.cs
=> fixed collision on non default layers

Assets/Models/Characters/Duif_Default_V4.fbx.meta, Assets/Scenes/BranchScenes/CrimeSceneQuest.unity
=> fixed bird colliders

Assets/Scripts/Entities/Animals/RatBehaviour.cs, Assets/Scripts/Entities/BaseEntity.cs
- Refactored fear using System.Linq.
- Entities calm down after not being scared.
- Minor adjustments due to review.
=> Fear calm down

Assets/Prefabs/Entities/PlayerV2.prefab, Assets/Prefabs/Entities/SirBoonkle.prefab, Assets/QuickOutline/Scripts/Outline.cs, Assets/Scenes/BranchScenes/QuestScenes/CemeteryScene.unity, Assets/Scripts/CutScene/Cutscene.cs, Assets/Scripts/Entities/BaseEntity.cs, Assets/Scripts/Entities/Special/SirBoonkleBehaviour.cs, Assets/Scripts/Entities/Special/SirBoonkleSpawnLocationBehaviour.cs
=> Fix boonkle

Assets/Scenes/BranchScenes/CrimeSceneQuest.unity, Assets/Scenes/BranchScenes/PreTutorialScene.unity
- Gave pretutorial new Player prefab
- Checked pre-tutorial
- Fixed ConversationSystemButton
=> Updated Pre-tutorial

Assets/Scripts/Entities/BaseEntity.cs, Assets/Scripts/Misc/SoundManager.cs, Assets/Scripts/Misc/ToggleAmbientSound.cs
- Fixed Animator warning for missing parameter
- Fixed the if statement checking ambient toggle
- Refactored the singleton a bit.
=> AmbientToggle

Assets/Scripts/Camera/CameraController.cs, Assets/Scripts/Player/LevitateBehaviour.cs, Assets/Scripts/Player/PlayerBehaviour.cs
=> Removed rotation and changed toggle button to RMB

Assets/Resources/ScriptableObjects/Conversations/Cemetery/Burt/Question01.asset, Assets/Scenes/BranchScenes/QuestScenes/CemeteryScene.unity, Assets/Scripts/Entities/Humans/EmmieBehaviour.cs, Assets/Scripts/Player/PlayerBehaviour.cs, Assets/Scripts/SceneTransition/CemeteryScene.cs
- Fixed transition trigger.
- Various fixes in cemetery and crime scene. (Mainly regarding conversations.)
=> Cemetery emmie transition trigger

Assets/Prefabs/UI/Popups/PreTutorialPopup.prefab, Assets/Scenes/BranchScenes/PreTutorialScene.unity
De veranderde teksten voor een popup in pretutorial
=> Changed popup text

Assets/Scripts/Entities/BaseEntityMovement.cs
=> Fixed infinite while, fixed loop music, enabled box collider

Assets/Prefabs/Entities/Animals/Rat.prefab, Assets/Prefabs/Entities/Animals/V2.meta, Assets/Prefabs/Entities/Animals/V2/BirdV2.prefab, Assets/Prefabs/Entities/Animals/V2/BirdV2.prefab.meta, Assets/Prefabs/Entities/Humans/V2.meta, Assets/Prefabs/Entities/Humans/V2/BlackPoliceManV2.prefab, Assets/Prefabs/Entities/Humans/V2/BlackPoliceManV2.prefab.meta, Assets/Prefabs/Entities/Humans/V2/CemeteryEmmieV2.prefab, Assets/Prefabs/Entities/Humans/V2/CemeteryEmmieV2.prefab.meta, Assets/Prefabs/Entities/Humans/V2/CrimeSceneEmmieV2.prefab, Assets/Prefabs/Entities/Humans/V2/CrimeSceneEmmieV2.prefab.meta, Assets/Prefabs/Entities/Humans/V2/EmmieV2.prefab, Assets/Prefabs/Entities/Humans/V2/EmmieV2.prefab.meta, Assets/Prefabs/Entities/Humans/V2/VincentTheVigilanteV2.prefab, Assets/Prefabs/Entities/Humans/V2/VincentTheVigilanteV2.prefab.meta, Assets/Prefabs/Entities/Humans/V2/WhitePoliceManV2.prefab, Assets/Prefabs/Entities/Humans/V2/WhitePoliceManV2.prefab.meta, Assets/Prefabs/Entities/Humans/V2/WhitePoliceWomanV2.prefab, Assets/Prefabs/Entities/Humans/V2/WhitePoliceWomanV2.prefab.meta, Assets/Prefabs/Entities/Humans/WhitePoliceWoman.prefab, Assets/Scenes/BranchScenes/EntityPivotResetBranch.unity, Assets/Scenes/BranchScenes/EntityPivotResetBranch.unity.meta
- Centered pivot point.
- Rotated entities toward z-axis.
- Copied components.
- Modified component values, where necessary.
=> Altered all entities pivot points.

Assets/Prefabs/Entities/Animals/V2/BirdV2.prefab, Assets/Prefabs/Entities/Humans/V2/BlackPoliceManV2.prefab, Assets/Prefabs/Entities/Humans/V2/CemeteryEmmieV2.prefab, Assets/Prefabs/Entities/Humans/V2/CrimeSceneEmmieV2.prefab, Assets/Prefabs/Entities/Humans/V2/EmmieV2.prefab, Assets/Prefabs/Entities/Humans/V2/VincentTheVigilanteV2.prefab, Assets/Prefabs/Entities/Humans/V2/WhitePoliceManV2.prefab, Assets/Prefabs/Entities/Humans/V2/WhitePoliceWomanV2.prefab, Assets/Scenes/BranchScenes/EntityPivotResetBranch.unity, Assets/Scripts/Entities/Animals/BirdBehaviour.cs, Assets/Scripts/Entities/BaseEntityMovement.cs, Assets/Scripts/Entities/Humans/EmmieBehaviour.cs
- Updated v2 prefabs of entities.
- Slightly altered BaseEntityMovement.
- Fixed missing animator bug.
=> Fixed bugs in prefabs

Assets/Scripts/Entities/BaseEntityMovement.cs
- Added a single line of code to rotate the entity toward the landing position.
=> Rotate entity to landing position.

Assets/Scripts/Entities/BaseEntityMovement.cs
- Rewrote method with Quaternion.
=> Updated rotation when jumping

Assets/Prefabs/Entities/Humans/V2/BlackPoliceManV2.prefab, Assets/Prefabs/Entities/Humans/V2/CrimeSceneEmmieV2.prefab, Assets/Prefabs/Entities/Humans/V2/VincentTheVigilanteV2.prefab, Assets/Prefabs/Entities/Humans/V2/WhitePoliceManV2.prefab, Assets/Prefabs/Entities/Humans/V2/WhitePoliceWomanV2.prefab
Patrick boi, de prefabs zitten er in, samen met de offmeshlinks. Het duurde lang, maar alles is getest. De offmeshlinks zijn op juiste hoogte ingesteld, met de juiste duratie. Verder kloppen de prefabs en werkt alles, voor zover getest, naar behoren. Accepteer bitte deze pullrequest, want ik ga lunchen met pa en Ryan wilt door. Danku
=> Crime scene off mesh links+new prefabs

Assets/Scenes/BranchScenes/CreditScene.unity
added art assets to credits scene (reused) + added audio team & playtesting team credits
=> Added Art assets to Credits + added audio team + playtesting credits

Assets/Scenes/BranchScenes/QuestScenes/CemeteryScene_2.unity, Assets/Scenes/BranchScenes/QuestScenes/CemeteryScene_2.unity.meta
added icons to cemetery and then duplicated cemetery to create cemetery_2. Cemetery 2 has different lighting + different states of assets
=> created cemetery 2

Assets/Resources/ScriptableObjects/Conversations/Ending/02 - Marcus & Emmie.meta, Assets/Scripts/Entities/BaseEntityMovement.cs
- Changed the distance of HadReachedDestination to a greater value.
=> Changed Pathfinding

Assets/Prefabs/UI/CluePickup.prefab, Assets/Resources/ScriptableObjects/Conversations/Ending/02 - Marcus & Emmie.meta, Assets/Scripts/Clues/WorldSpaceClue.cs, Assets/Scripts/UI/PopupMenu/Popup.cs
- Updated CrimeScene
- Altered Popups
- Updated WorldSpaceClue
- Altered Clue Popup Canvas
=> Added Dynamic clues

Assets/Models/Doors/BakerDoor.fbx.meta, Assets/Models/Party/BeerBottle.fbx.meta, Assets/Models/Party/BeerCrate_Empty-ish.fbx.meta, Assets/Models/Party/Board1.fbx.meta, Assets/Models/Party/Board2.fbx.meta, Assets/Models/Party/DrinkCrate.fbx.meta, Assets/Models/Party/Open_BeerBottle.fbx.meta, Assets/Models/Party/Sauce.fbx.meta, Assets/Models/Party/WineBottle.fbx.meta, Assets/Models/Party/WineGlass.fbx.meta, Assets/Scripts/Clues/WorldSpaceClue.cs, Assets/Scripts/UI/PopupMenu/Popup.cs
Fixed i hope all the Read/Write enabled meshes
=> Fixed Clue pickup Popup

Assets/Scripts/Entities/Abilities/ClimbBehaviour.cs, Assets/Scripts/Entities/Abilities/GlideBehaviour.cs, Assets/Scripts/Entities/Animals/BirdBehaviour.cs, Assets/Scripts/Entities/Animals/RatBehaviour.cs, Assets/Scripts/Entities/BaseEntity.cs
When the ability button is clicked, but no ability is toggled, the player can still leave the possessed target.
=> Fixed bug when leaving possesion

Assets/Scripts/Camera/CameraController.cs
=> Removed RMB mouse unlock

Assets/Materials/Textured/Grave Stone 3.mat, Assets/Materials/Textured/GraveStone2.mat, Assets/Materials/Textured/Gravestone1.mat, Assets/Materials/Textured/M_Annie.mat, Assets/Materials/Textured/M_Bird 1.mat, Assets/Materials/Textured/M_Bird.mat, Assets/Materials/Textured/M_Cloth.mat, Assets/Materials/Textured/M_Coal.mat, Assets/Materials/Textured/M_Flower2.mat, Assets/Materials/Textured/M_Glass.mat, Assets/Materials/Textured/M_Glass_Blood.mat, Assets/Materials/Textured/M_Groundskeeper.mat, Assets/Materials/Textured/M_Julia_Grave.mat, Assets/Materials/Textured/M_Sally.mat, Assets/Materials/Textured/M_SaltySticks.mat, Assets/Materials/Textured/M_Sign.mat, Assets/Materials/Textured/M_Steak.mat, Assets/Materials/Textured/M_Tree_Willow.mat, Assets/Materials/Textured/M_knife.mat, Assets/Materials/Textured/Tree1_Leaves_1 1.mat, Assets/Materials/Textured/Tree1_Leaves_1.mat, Assets/Materials/Textured/Tree1_Leaves_2.mat, Assets/Materials/Textured/Tree2_Leaves_1.mat, Assets/Materials/Textured/Tree2_Leaves_2.mat, Assets/Materials/Textured/Tree2_Leaves_3 1.mat, Assets/Scenes/BranchScenes/QuestScenes/CemeteryScene_2.unity
materials aangepast naar de nieuwe pipeline
=> fixed materials particles and chest

Assets/Prefabs/UI/CluePickup.prefab, Assets/Scripts/Clues/WorldSpaceClue.cs
- Popup screen for last popup will be shown
- Changed scaling op popup window to fit text
=> Fix last clue pickup

Assets/Prefabs/Entities/Humans/Bort.prefab, Assets/Prefabs/Entities/Humans/Burt.prefab, Assets/Prefabs/Entities/Humans/V2/Annie.prefab, Assets/Prefabs/Entities/Humans/V2/BlackPoliceManV2.prefab, Assets/Prefabs/Entities/Humans/V2/EmmieV2.prefab, Assets/Prefabs/Entities/Humans/V2/Sally.prefab, Assets/Prefabs/Entities/Humans/V2/WhitePoliceManV2.prefab, Assets/Prefabs/Entities/Humans/V2/WhitePoliceWomanV2.prefab, Assets/Scripts/Entities/BaseEntity.cs
- Updated all prefabs: new FearEmpty
- Added additional checks for non-existent FearEmpty
=> Updated FearAngle

Assets/Resources/ScriptableObjects/Conversations/CrimeScene/Annie/Question01.asset, Assets/Resources/ScriptableObjects/Conversations/CrimeScene/Dana/Question01.asset, Assets/Resources/ScriptableObjects/Conversations/CrimeScene/Emmie_CrimeScene/Question01.asset, Assets/Resources/ScriptableObjects/Conversations/CrimeScene/Sally/Question01.asset, Assets/Resources/ScriptableObjects/Conversations/CrimeScene/Vincent/Question01.asset, Assets/Scripts/Enums/CharacterType.cs
- crime scene: Als je met Annie praat staat er dat je boolia heet
- Crime scene: Sally's default responses en match conversation werken niet
- annie's default responses werken niet
- Crime scene: Vincent moet matchen met Emmie, Sally, Annie, Burt, en Bort (nu matcht ie alleen met Emmie)
- Sally clue conversation
- annie clue conversation
- dana clue conversation
- emmie clue conversation
- vincent clue conversation
- cops now have unique names
=> Fixed broken crime scene dialogue

Assets/Models/Cemetary/MausoleumCoffin_Bottom_V2.fbx.meta, Assets/Models/Cemetary/MausoleumCoffin_Lid_V2.fbx.meta, Assets/Prefabs/Models/IronFence_Broken_V2.prefab, Assets/Resources/ScriptableObjects/Conversations/Ending/03_ Boolia_Emmie/Question01.asset, Assets/Scenes/BranchScenes/QuestScenes/CemeteryScene_1.unity
CrimeScene:
- Fixed the invisible wall from the iron fence.
- Fixed missing elements in ending and ending dialogue after cutscene.
- Fixed material from whitepolicewoman.
- Adjusted ending dialogue flow, now the right dialogue is played after a certain answer.
Cemetery_1:
- Fixed start position of camera for cutscene.
- Readded burt and bort, now they dont glitch anymore.
- Fixed some read/write issues.
=> Bug fixes crime scene and cemetery
